CIA: Central Intelligence Agency
The Agency: Central Intelligence Agency
WPAFB: Wright-Patterson AFB
Wright Patterson AFB: Wright-Patterson AFB
DoD: Department of Defense
US DoD: Department of Defense
