site_name: UAP Gerb Archive
site_url: https://enisi.github.io/ubiquitous-happiness/
theme:
  name: material
nav:
- Video Index: video-index.md
- Videos:
  - 1997 ALIEN REPRODUCTION VEHICLE ENCOUNTER AT 29 PALMS, CA - THE TESTIMONY OF SGT RODERICK CASTLE: video-pages/ShoUyC1aip0.md
  - The 1948 Aztec, New Mexico UFO Crash Retrieval: video-pages/QJxbyu-9Tj0.md
  - UFO Legacy Programs - Science Applications International Corporation (SAIC): video-pages/9p99lTsC7wQ.md
  - 1997 Peru UFO Crash Retrieval - the Story of Jonathan Weygandt: video-pages/7Jc2G5aEH0A.md
  - US Navy UFO Crash Retrieval & Reverse Engineering Programs: video-pages/H9GSqOEvoBE.md
  - Deep Underground Military Bases (D.U.M.Bs.) - UFO Legacy Programs: video-pages/7Ats0lIy3Lo.md
  - Dugway Proving Ground - UFO Legacy Programs: video-pages/rePrVmR6a68.md
  - UFO Legacy Programs - Northrop Grumman: video-pages/E-GleS2aGj0.md
  - Philip J. Corso - US Army UFO Technology Research & Development: video-pages/_sv0Otxtcn4.md
  - Alien Reproduction Vehicle - TR-3B and the Flying Triangles: video-pages/B7JP0uX0GwY.md
  - 'Post UAP Hearing Live Stream: Time in DC, Immaculate Constellation, & More': video-pages/t9cLswYmWzU.md
  - Alien Reproduction Vehicle - the Testimony of Mark McCandlish: video-pages/wF07QMm6joE.md
  - Livestream and Q&A with Michael Herrera 10/6/24: video-pages/AyA2SfFK89Q.md
  - UAP Reverse Engineering at Edwards Air Force Base [Redacted List Vol.2]: video-pages/U_LSMLGBDNg.md
  - 9/29/24 Bush/Cheney Historical Connections to UFO Legacy Crash Retrieval Programs Ft. VolarRecords: video-pages/t85t8QpTsD4.md
  - 10K Live! UAPDA, Crash Retrieval Research, Q&A and More: video-pages/jNC-0dmH5BQ.md
  - The 1965 Kecksburg, Pennsylvania UFO Crash: video-pages/rgBTMzFd-hg.md
  - 9/8/24 Discussing Steven Greer London Live Event: video-pages/3iWLTyhdyf4.md
  - 9/1/24 Discussing WD Memo, 2004 JSOC Case and Q&A: video-pages/ZFUneP18LVI.md
  - The Majestic-12 Documents [With Ryan S. Wood]: video-pages/vzB87RJkQVU.md
  - The 1974 Coyame, Mexico UFO Crash: video-pages/bL3tMByq_WM.md
  - 7/20/24 Discussing Cases and Q&A: video-pages/1m0oJD59eXQ.md
  - "Off-World Technologies Division \u2013 UAP Technology Reverse Engineering": video-pages/QJ215I85d5M.md
  - Michael Herrera - Insights into UAP Encounter and Black Program Insiders: video-pages/4EMO38JUfVE.md
  - Live with Joey: video-pages/azC7-UBRBSw.md
  - UAP Gerb Live Stream: video-pages/2Goib1eosJQ.md
  - '"US Special Forces Confession - I Recovered Crashed UFOs": Fact or Fiction?': video-pages/DcvuglS7ps4.md
  - UFO Whistleblowers [Vol.2]: video-pages/9Xk4X41yl2M.md
  - The 1950s Del Rio, Texas UFO Crashes: video-pages/8S9qdRWSnD8.md
  - UFO Whistleblowers [Vol.1]: video-pages/EKEZ2BClIb0.md
  - 'USO Case Book: Unidentified Submerged Objects Throughout History': video-pages/Yn-83KbgRN8.md
  - USO - Unidentified Submerged Objects: video-pages/U-jrx_giINA.md
  - Dr. Robert Sarbacher & the US Government's Secret UFO Crash Retrieval Group: video-pages/R7DyJRf14nU.md
  - 'Michael Herrera: UFO Whistleblower (ft. Joeyisnotmyname)': video-pages/6DyTfIV87Ck.md
  - The 1933 Magenta, Italy UFO Crash: video-pages/FGiwgyLY7Aw.md
  - "The Physics of UFOs\u2013 Dr. Kevin Knuth": video-pages/inyw4Vfu7Z0.md
  - The 1953 Kingman, Arizona UFO Crash: video-pages/41V4Pf_8oo4.md
  - "FASTWALKERS \u2013 UFOs Outside Earth": video-pages/Tubx-CaAaOs.md
  - UFOs in the Private Sector - Lockheed Martin: video-pages/tVdzvvbbHW4.md
  - UFOs in the Private Sector - Battelle Memorial Institute: video-pages/tISTJRPOqFo.md
  - 'SOL Foundation: Karl Nell - A Key Figure in UAP Disclosure': video-pages/kKbSIfc7N7Q.md
  - Incredible UFO Footage - METAPOD: video-pages/i6fitvV-aO0.md
  - The Origin of the UFO Stigma: video-pages/xKArN8S9bnM.md
  - Incredible UFO Footage - FLYBY: video-pages/qD1KnudMCO0.md
  - Global Air Force UFO Encounters You've Probably Never Heard of: video-pages/6cVe-hdMTCE.md
  - UFOs and Nuclear Weapons - A Fascinating Connection: video-pages/-DK2u8HlhDE.md
  - The Modern Day UFO Disinformation Agent - Dr. Sean Kirkpatrick's Lies: video-pages/hK24ZdkvwN4.md
  - MOON DUST - The Pentagon's Secret UFO Programs: video-pages/6ZuHLgVtKu8.md
  - The First Commercial Flight Grounded Due to UFOs: video-pages/K_BZkOAw6E0.md
  - The Marines Who Got too Close to UFOs: video-pages/HnxylCl68Tg.md
  - The Alien and UFO Obscure Oddities Iceberg (Level 2): video-pages/9FL04mqyZxk.md
  - The Alien and UFO Obscure Oddities Iceberg (Level 1): video-pages/1en219Vk9K4.md
  - The Wilson Davis Memo and US Secret UFO Reverse Engineering Programs: video-pages/yIqkazIZh9I.md
- Entities: entities.md
markdown_extensions:
- meta
- admonition
- pymdownx.details
plugins:
- search
