site_name: UAP Gerb Archive
theme:
  name: material
nav:
  - Video Index: video-index.md
  - Videos:
      - "Video pages appear under 'video-pages' automatically": video-index.md
markdown_extensions:
  - admonition
  - pymdownx.details
