name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    env:
      YT_API_KEY: ${{ secrets.YT_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm || true

      - name: (Optional) Fetch metadata via API
        if: ${{ env.YT_API_KEY != '' }}
        run: |
          python scripts/ingest_via_api.py "@UAPGerb"

      - name: Generate site content (NER disabled by default)
        run: |
          export ENABLE_NER=0
          python scripts/build.py

      - name: Build MkDocs
        run: |
          mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
